from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Define two example embeddings (vectors) as NumPy arrays
# In a real scenario, these would be generated by an embedding model
def recommendation_generator(embeddings):
    resume_embedding = embeddings[0].reshape(1, -1)
    jd_embeddings = embeddings[1:len(embeddings)]

    similarity_score = np.zeros(len(jd_embeddings))
    # Calculate the cosine similarity
    for i, jd in enumerate(jd_embeddings):
        jd__embedding = jd.reshape(1, -1)
        similarity_score[i] = cosine_similarity(resume_embedding, jd__embedding)[0][0]
    
    # Sort similarity_score in descending order and print the indices of the top three values
    recommendations = sorted(range(len(similarity_score)), key=lambda i: similarity_score[i], reverse=True)[:3]
    return recommendations